# Generated by Django 3.1 on 2020-08-23 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmark', '0004_bookmark_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmark',
            name='desc',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
